name: Runner Test

on:
  push:
    branches: [ main ]

jobs:
  test-self-hosted:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Say hello
        run: echo "Hola desde el runner self-hosted en EC2 🎉"