name: Runner Test

on:
  push:
    branches: [ main ]

jobs:
  self-hosted-check:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print message
        run: echo "✅ Hola desde tu runner en EC2"
